### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by fcouceiro** [clubeprogramacao/Website#2]
I've create a new Course with success (returned id=1) and then I tried to create a new User supplying the course_id as 1, but it returned this error:

![Error image](http://s33.postimg.org/jkflspzrz/Captura_de_ecra_2016_05_25_a_s_15_06_22.png)

**Comment by rscmendes** [comment]
Had to add courses_id as fillable to the User Model as they are being mass assigned. 
Related: http://stackoverflow.com/questions/29189311/laravel-5-integrity-constraint-violation-1452-cannot-add-or-update-a-child-row

Edit: all other columns had to be added as fillable so that all data could be sent in the request we were using ->Uses mass assignment.
